---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/10/8 11:27
---

local execute = os.execute

local dir = "test"
local b, err = execute("mkdir " .. dir)
if not b then
    print("mkdir failed: " .. err)
end

local f, err = io.open(dir)

print("...")
