---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/7 16:16
---

--[[

while 循环语法
while(condition)
do
   statements
end

--]]
a = 5
while (a >= 0)
do
    print(a)
    a = a - 1
end


--[[

Lua 中 for 循环分为两类
- 数值 for 循环
- 泛型 for 循环

 for 语法
    for var_name=exp1,exp2,exp3 do
        statements
    end
    - var 从 exp1 变化到 exp2，每次变化以 exp3 为步长递增 var，并执行一次 "执行体"。exp3 是可选的，如果不指定，默认为1

--]]
for i = 1, 3 do
    print(i)
end

print(i)  --- nil

for j = 3, 1, -1 do
    print(j)
end

