---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/7 15:53
---

--- 大于等于 0 的 number 在条件表达式中表示 true
if 0 or 3 then
    print("0 is true")
end

a = 3
if (a < 5) then
    print(a, "小于 5")
end

a = 10
if (a < 5) then
    print(a, "小于 5")
else
    print(a, "大于等于5")
end
