---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/7 16:48
---

--- 使用构造器表达式创建 table
local t = {}

t[1] = "Lua"
print(t[1])  --- Lua
--- 未初始化的表元素为 nil
print(t[2])  --- nil

t = nil --- 移除引用，自动垃圾回收


local t2 = {}

t2["name"] = "apisix"
print(t2.name)  --- 点分形式表示 用字符串来索引表，即 t2["name"] 等价于 t2.name

local days = {
    "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday",
    "Friday", "Saturday"
}
print(days[1], days[2], days[3], days[4], days[5], days[6], days[7])

local t4 = {
    x = 10,
    y = 20
}

print(t4.x, t4.y)
print(t4["x"], t4["y"])

local polyline = {
    color = "blue",
    thickness = 2,
    npoints = 4,
    { x = 0, y = 0 },  --- polyline[1]
    { x = -10, y = 0 } --- polyline[2]
}
print(polyline[1].x, polyline[1].y, polyline[2].x, polyline[2].y)

local t5 = {}
for i = 1, 10 do
    t5[i] = i
end
print("table t5 len= ", #t5)

local t6 = {}
for i = 1, 10, 2 do
    --print(i)
    t6[i] = i
end
print("table t6 len= ", #t6)
print(t6[2], t6[3], t6[4], t6[5])

local t7 = {}
for i = 2, 10, 2 do
    --print(i)
    t7[i] = i
end
print("table t7 len= ", #t7)
print(t7[2], t7[3], t7[4], t7[5])

for k, v in pairs(days) do
    print(k, v)
end

for k, v in pairs(t7) do
    print(k, v)
end

for k, v in ipairs(t6) do
    print(k, v)
end

for i = 1, #days do
    print("day[" .. i .. "] = ", days[i])
end