---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/6 19:52
---

local M = {}

--- 模块变量
M.ModuleName = "模块M"

local s = 1
if s >= 1 then
    print("require后执行")
end

--- 私有函数
local function Add(a, b)
    return a + b
end
--- 把 Add 加入到模块中，加载模块后可使用
M.Add = Add


--- 私有函数
local function Sub(a, b)
    return a + b
end

return M