---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/27 15:56
---

--- 导入标准库 math
local math = require("math")
--- 导入标准库 math 中的函数
local sin = require("math").sin
--- 导入标准库 string
local string = require "string"

print(math.sin(3.14))
print(sin(3.14))


