---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/7 15:17
---

--- 数据类型

var1 = 5
var2 = 10.0
var3 = "data"
var4 = false

print(var1, var2, var3, var4)
print(var2, " type= ", type(var2))
print(var3, " type= ", type(var3))
print(var4, " type= ", type(var4))

--- 赋值
var11, var12 = 2
var21, var22, var23 = 2, "data", true, 3
print(var11, var12)
print(var21, var22, var23)

