---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/7 15:37
---

--[[

Lua 函数的定义格式如下：
optional_function_scope function function_name(argument1, argument2, argument3..., argumentn)
    function_body
    return result_params_comma_separated
end

- optional_function_scope：指定函数的作用范围，即指定函数为全局函数还是局部函数，默认为全局函数，定义局部函数可使用关键字 local
- function_name：指定函数名
- argument1, argument2, argument3..., argumentn：函数形参，不指定形参类型
- function_body：函数体
- result_params_comma_separated：函数返回值，支持多返回值，以逗号隔开
--]]

--- 函数需要先定义才能使用
function Add(num1, num2)
    result = num1 + num2
    return result
end

sum = Add(2, 3)
print(sum, result)
