---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/9/8 15:13
---

local io_open = io.open

---
---
local file, err = io_open("test.log", "a+")
if not err then
    -- 文件不存在或无权限打开文件
    print(err)
end

