---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/8 17:22
---

local etcd = require("resty.etcd")

etcd_client = etcd.new({
    hosts = {
        "http://172.29.147.27:2379"
    },
    prefix = "/v3alpha"
})

local resp, err = _etcd:readdir(self.prefix)
dump(resp)

function dump(o)
    if type(o) == 'table' then
        local s = '{ '
        for k,v in pairs(o) do
            if type(k) ~= 'number' then k = '"'..k..'"' end
            s = s .. '['..k..'] = ' .. dump(v) .. ','
        end
        return s .. '} '
    else
        return tostring(o)
    end
end