---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieym.
--- DateTime: 2023/3/7 15:57
---

A, B = 10, 3

print(A + B)
print(A - B)
print(A * B)
print(A/B)
print(A//B)
print(A % B)
print(A ^ B)
--[[ result
13
7
30
3.3333333333333
3
1
1000.0
--]]